/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ticketmaster.ticketplusclient.gui;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.*;

/**
 * Dashboard para usuarios con rol estándar (USER).
 *
 * <p>El usuario únicamente ve sus propios tickets abiertos, en progreso
 * o pendientes de respuesta. El listado es gestionado por
 * {@link TicketListPanel}, que aplica el filtro de visibilidad según el
 * rol obtenido de {@link com.ticketmaster.ticketplusclient.session.SessionManager}.</p>
 *
 * <p>Vistas registradas:</p>
 * <ul>
 *   <li>{@code "tickets"} — listado de tickets propios ({@link TicketListPanel}).</li>
 *   <li>{@code "newTicket"} — formulario de apertura de nueva incidencia ({@link NewTicketPanel}).</li>
 *   <li>{@code "detail"} — detalle de ticket ({@link TicketDetailPanel}),
 *       recreado dinámicamente en cada apertura.</li>
 * </ul>
 *
 * @author Erik
 * @see DashboardBaseGUI
 */
public class DashboardUserGUI extends DashboardBaseGUI {
    
    private StatsPanel statsPanel;

    /**
     * Crea el dashboard del usuario estándar.
     * Delega la inicialización completa al constructor base,
     * que invoca el hook {@link #setupRoleDashboard()}.
     */
    public DashboardUserGUI(){
        super();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Registra los paneles del usuario y muestra el listado de tickets al arrancar.
     *
     * <p>El {@code Consumer<Long>} inyectado en {@link TicketListPanel} es
     * {@link #showTicketDetail}, que recrea el panel de detalle con el ticket
     * correcto cada vez que se selecciona uno.</p>
     */
    protected void setupRoleDashboard() {
        ticketListPanel = new TicketListPanel(
                        () -> {
                                newTicketPanel.reset();
                                showCenterPanel("newTicket");
                        },
                        this::showTicketDetail
        );
        
        statsPanel = new StatsPanel(() -> showCenterPanel("tickets"), true);
        
        addCenterPanel(
                ticketListPanel,
                "tickets"
        );
        addCenterPanel(
                new NewTicketPanel(
                        () ->showCenterPanel("tickets"),
                        () ->showCenterPanel("tickets")
                ),
                "newTicket"
        );
        addCenterPanel(statsPanel,      "stats");
        showCenterPanel("tickets");
    }
    
    /**
     * Abre el panel de detalle para el ticket con el identificador indicado.
     *
     * <p>Elimina el panel de detalle anterior si existía, crea uno nuevo
     * y lo muestra. El botón "Back" del detalle navega de vuelta a
     * {@code "tickets"}.</p>
     *
     * @param ticketId identificador del ticket a mostrar
     */
    private void showTicketDetail(Long ticketId){
        for(Component c : getCenterPanel().getComponents()){
            if(c instanceof TicketDetailPanel){
                getCenterPanel().remove(c);
                break;
            }
        }
        addCenterPanel(
                new TicketDetailPanel(ticketId, () -> {
                    ticketListPanel.refresh();
                    showCenterPanel("tickets");
                
                }),
                "detail"
        );
        showCenterPanel("detail");
    }
    
    /**
     * Boton Home - Siempre vuelve al listado de tickets.
     */
    @Override
    protected void onSidebarButtonHome(){
        showCenterPanel("tickets");
    }
    
    /**
     * Boton 1 - Navega a...
     */
    @Override
    protected void onSidebarButton1(){
        //Aplicar funcionalidad proximamente
    }
    
    /**
     * Boton 2 - Navega a...
     */
    @Override
    protected void onSidebarButton2(){
        statsPanel.refresh();
        showCenterPanel("stats");
    }
    
    /**
     * Boton 3 - Navega a...
     */
    @Override
    protected void onSidebarButton3(){
        //Aplicar funcionalidad proximamente
    }
    
    /**
     * Boton 4 - Navega a...
     */
    @Override
    protected void onSidebarButton4(){
        //Aplicar funcionalidad proximamente
    }
    
    /**
     * Boton 5 - Navega a...
     */
    @Override
    protected void onSidebarButton5(){
        //Aplicar funcionalidad proximamente
    }

    /**
     * Construye el panel de estadísticas del usuario con tres tarjetas:
     * tickets abiertos, en espera de respuesta y cerrados.
     *
     * @return panel {@link JPanel} con el layout de estadísticas en cuadrícula
     */
    private JPanel buildStatsPanel() {
        JPanel panel = new JPanel(new GridLayout(1, 3, 10, 0));
        panel.setBackground(new Color(34, 40, 44));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        panel.add(buildStatCard("Open tickets", "1"));
        panel.add(buildStatCard("Awaitin Reply", "2"));
        panel.add(buildStatCard("Closed", "3"));

        return panel;
    }

    /**
     * Crea una tarjeta de estadística individual con título y valor numérico.
     *
     * @param title etiqueta descriptiva de la estadística
     * @param value valor numérico a mostrar en la tarjeta
     * @return panel {@link JPanel} con la tarjeta de estadística maquetada
     */
    private JPanel buildStatCard(String title, String value) {
        JPanel card = new JPanel(new BorderLayout());
        card.setBackground(new Color(21, 25, 28));
        card.setBorder(BorderFactory.createEmptyBorder(12, 16, 12, 16));
        card.setPreferredSize(new Dimension(0, 80));

        JLabel titleLabel = new JLabel(title);
        titleLabel.setForeground(new Color(180, 180, 180));

        JLabel valueLabel = new JLabel(value);
        valueLabel.setForeground(Color.WHITE);
        valueLabel.setFont(valueLabel.getFont().deriveFont(28f));

        card.add(titleLabel, BorderLayout.NORTH);
        card.add(valueLabel, BorderLayout.CENTER);
        return card;
    }

    /**
     * Construye el panel principal de tickets del usuario.
     * Actualmente muestra un marcador de posición; se completará en sprints
     * posteriores con la lista de tickets del usuario autenticado.
     *
     * @return panel {@link JPanel} del área de tickets (placeholder)
     */
    private JPanel buildTicketPanel() {
        JPanel panel = new JPanel();
        panel.setBackground(new Color(21, 25, 28));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JLabel placeholder = new JLabel("....");
        placeholder.setForeground(new Color(120, 120, 120));
        panel.add(placeholder);

        return panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
