/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ticketmaster.ticketplusclient.gui;

import com.ticketmaster.ticketplusclient.session.AuthService;
import com.ticketmaster.ticketplusclient.session.SessionManager;
import java.awt.BorderLayout;
import java.awt.CardLayout;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 * Ventana base del panel de control (dashboard) de la aplicación TicketPlus.
 *
 * <p>Implementa el patrón <b>Template Method</b>: define la estructura común del
 * dashboard (barra lateral de navegación, cabecera con bienvenida y botón de logout,
 * panel central) y declara el método {@link #setupRoleDashboard()} como punto de
 * extensión para que las subclases ({@link DashboardAgentGUI} y {@link DashboardUserGUI})
 * personalicen el contenido del área central según el rol del usuario.</p>
 *
 * <p>Tras un logout, reinicia el cliente Retrofit mediante
 * {@link com.ticketmaster.ticketplusclient.api.ClientAPI#reset()} y abre de nuevo
 * la ventana de {@link LoginGUI}.</p>
 *
 * @author Christian
 * @see DashboardAgentGUI
 * @see DashboardUserGUI
 * @see AuthService
 * @see SessionManager
 */
public class DashboardBaseGUI extends javax.swing.JFrame {

    /** Servicio de autenticación utilizado para gestionar el logout. */
    private final AuthService authService;
    
    /**
     * Layour de tarjetas que gestiona la navegacion del area central ({@code pnlCCenter}).
     * Se inicializa en {@link #setupCenterLayout()} antes del hook {@link #setupRoleDashboard()}
     */
    private CardLayout centerCardLayout;
    
    /**
    * Referencia al panel de listado de tickets, compartida por ambos roles.
    * Se asigna en {@link #setupRoleDashboard()} de cada subclase y se usa
    * para refrescar la lista tras crear o modificar un ticket.
    */
    protected TicketListPanel ticketListPanel;
    
    /**
    * Referencia al panel de creacion de ticket, compartida por ambos roles.
    * Se asigna en {@link #setupRoleDashboard()} de cada subclase y se usa
    * para refrescar la lista tras crear o modificar un ticket.
    */
    protected NewTicketPanel newTicketPanel;
    
    /**
     * Crea una nueva instancia del dashboard base, inicializando el servicio de
     * autenticación, los componentes gráficos, la barra lateral, la información
     * de sesión y delegando la configuración específica de rol al método
     * {@link #setupRoleDashboard()}.
     */
    public DashboardBaseGUI() {
        
        this.authService = new AuthService();
        
        initComponents();
        setupCenterLayout();
        setupSidebarButtons();
        sessionInfo();
        setupRoleDashboard();
        pack();
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(900, 600));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonLogout = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlCTop = new javax.swing.JPanel();
        jLabelWelcomeUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlCCenter = new javax.swing.JPanel();
        pnlCBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(21, 25, 28));
        pnlSide.setPreferredSize(new java.awt.Dimension(80, 0));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 150));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        jButtonHome.setBackground(new java.awt.Color(34, 40, 44));
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-organización-40.png"))); // NOI18N
        jButtonHome.setFocusPainted(false);
        jButtonHome.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonHome);

        pnlSide.add(jPanel2);

        jButton1.setBackground(new java.awt.Color(34, 40, 44));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton1);

        jButton2.setBackground(new java.awt.Color(34, 40, 44));
        jButton2.setFocusPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton2);

        jButton3.setBackground(new java.awt.Color(34, 40, 44));
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton3);

        jButton4.setBackground(new java.awt.Color(34, 40, 44));
        jButton4.setFocusPainted(false);
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton4);

        jButton5.setBackground(new java.awt.Color(34, 40, 44));
        jButton5.setFocusPainted(false);
        jButton5.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton5);

        jPanel3.setBackground(new java.awt.Color(21, 25, 28));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 150));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        jButtonLogout.setBackground(new java.awt.Color(34, 40, 44));
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salida-40.png"))); // NOI18N
        jButtonLogout.setFocusPainted(false);
        jButtonLogout.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLogout);
        jButtonLogout.getAccessibleContext().setAccessibleDescription("");

        pnlSide.add(jPanel3);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(34, 40, 44));
        pnlCenter.setPreferredSize(new java.awt.Dimension(697, 507));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlCTop.setBackground(new java.awt.Color(34, 40, 44));
        pnlCTop.setPreferredSize(new java.awt.Dimension(0, 100));

        jLabelWelcomeUser.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabelWelcomeUser.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Showing all task for today");

        javax.swing.GroupLayout pnlCTopLayout = new javax.swing.GroupLayout(pnlCTop);
        pnlCTop.setLayout(pnlCTopLayout);
        pnlCTopLayout.setHorizontalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelWelcomeUser))
                .addContainerGap(658, Short.MAX_VALUE))
        );
        pnlCTopLayout.setVerticalGroup(
            pnlCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelWelcomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlCTop, java.awt.BorderLayout.NORTH);

        pnlCCenter.setBackground(new java.awt.Color(34, 40, 44));

        javax.swing.GroupLayout pnlCCenterLayout = new javax.swing.GroupLayout(pnlCCenter);
        pnlCCenter.setLayout(pnlCCenterLayout);
        pnlCCenterLayout.setHorizontalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        pnlCCenterLayout.setVerticalGroup(
            pnlCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCCenter, java.awt.BorderLayout.CENTER);

        pnlCBottom.setBackground(new java.awt.Color(34, 40, 44));
        pnlCBottom.setPreferredSize(new java.awt.Dimension(0, 100));

        javax.swing.GroupLayout pnlCBottomLayout = new javax.swing.GroupLayout(pnlCBottom);
        pnlCBottom.setLayout(pnlCBottomLayout);
        pnlCBottomLayout.setHorizontalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        pnlCBottomLayout.setVerticalGroup(
            pnlCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCBottom, java.awt.BorderLayout.SOUTH);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        onSidebarButton1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        onSidebarButton2();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        onSidebarButton3();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        onSidebarButton4();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        onSidebarButton5();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        onSidebarButtonHome();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        doLogout();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * Inicializa el {@link CardLayout} sobre {@code pnlCCenter}.
     */
    private void setupCenterLayout(){
        centerCardLayout = new CardLayout();
        pnlCCenter.setLayout(centerCardLayout);
    }
    
    /**
     * Registra un panel en el area central bajo un nombre de tarjeta.
     * 
     * @param panel panel a registrar
     * @param cardName nombre clave para referenciarlo con {@link #showCenterPanel}
     */
    protected void addCenterPanel(JPanel panel, String cardName){
        pnlCCenter.add(panel, cardName);
    }
    
    /**
     * Muestra el panel registrado bajo el nombre indicado en el area central.
     * 
     * @param cardName nombre con el que se registro el panel en {@link #addCenterPanel}
     */
    protected void showCenterPanel(String cardName){
        centerCardLayout.show(pnlCCenter, cardName);
    }
    
    /**
     * Devuelve el panel central ({@code pnlCCenter}) gestionado por le CardLayout.
     * Disponible para subclases que necesiten añadir componentes directamente.
     *
     * @return el {@link JPanel} central ({@code pnlCCenter}) del dashboard
     */
    protected JPanel getCenterPanel(){
        return pnlCCenter;
    }
    
    /**
     * Hool de inicializacion de rol.
     * 
     * <p>Las subclases sobrescriben este metodo para registrar sus paneles con
     * {@link #addCenterPanel} y mostrar la vista inicial con {@link #showCenterPanel}.</P>
     * 
     */
    protected void setupRoleDashboard(){}
    
    /**
     * Acción del botón Home (posición superior de la sidebar).
     * Las subclases sobreescriben este método para definir su navegación.
     */
    protected void onSidebarButtonHome(){}

    /**
     * Acción del botón 1 de la barra lateral.
     * Las subclases sobreescriben este método para definir su navegación.
     */
    protected void onSidebarButton1(){}

    /**
     * Acción del botón 2 de la barra lateral.
     * Las subclases sobreescriben este método para definir su navegación.
     */
    protected void onSidebarButton2(){}

    /**
     * Acción del botón 3 de la barra lateral.
     * Las subclases sobreescriben este método para definir su navegación.
     */
    protected void onSidebarButton3(){}

    /**
     * Acción del botón 4 de la barra lateral.
     * Las subclases sobreescriben este método para definir su navegación.
     */
    protected void onSidebarButton4(){}

    /**
     * Acción del botón 5 de la barra lateral.
     * Las subclases sobreescriben este método para definir su navegación.
     */
    protected void onSidebarButton5(){}
    
    /**
     * Configura el layout y el comportamiento visual de los botones de la barra
     * lateral de navegación, incluyendo el efecto hover (cambio de color al
     * pasar el ratón) mediante un {@link MouseListener} anónimo.
     */
    private void setupSidebarButtons(){
        
        pnlSide.removeAll();
        pnlSide.setLayout(new BorderLayout());
        
        //Boton Home - Anclado al norte del sidebar.
        jPanel2.setLayout(new GridBagLayout());
        jPanel2.setPreferredSize(new Dimension(80, 80));
        pnlSide.add(jPanel2, BorderLayout.NORTH);
        
        //Botones del panel central - Centrados verticalmente.
        JPanel pnlMiddle = new JPanel();
        pnlMiddle.setBackground(new Color(21, 25, 28));
        pnlMiddle.setLayout(new BoxLayout(pnlMiddle, BoxLayout.Y_AXIS));
        
        pnlMiddle.add(Box.createVerticalGlue());
        JButton[] navButtons = {jButton1, jButton2, jButton3, jButton4, jButton5};
        for(JButton button : navButtons){
            button.setAlignmentX(Component.CENTER_ALIGNMENT);
            button.setMaximumSize(new Dimension(40, 40));
            pnlMiddle.add(button);
            pnlMiddle.add(Box.createRigidArea(new Dimension(0, 8)));
        }
        pnlMiddle.add(Box.createVerticalGlue());
        pnlSide.add(pnlMiddle, BorderLayout.CENTER);
        
        //Boton Logout - Anclado al sur.
        jPanel3.setLayout(new GridBagLayout());
        jPanel3.setPreferredSize(new Dimension(80,80));
        jPanel3.setBorder(BorderFactory.createEmptyBorder(0,0,15,0));
        pnlSide.add(jPanel3, BorderLayout.SOUTH);

        for (JButton button : navButtons) {
            button.setBackground(new Color(21, 25, 28));
            button.setUI(new BasicButtonUI());
            button.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    button.setBackground(new Color(54, 81, 207));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    button.setBackground(new Color(21, 25, 28));
                }

            });
        }
    }
    
    /**
     * Actualiza la etiqueta de bienvenida de la cabecera con el nombre del usuario
     * de la sesión activa obtenido de {@link SessionManager}.
     */
    private void sessionInfo(){
        SessionManager session = SessionManager.getInstance();
        if(session.isLoggedIn()){
            jLabelWelcomeUser.setText("Welcome "+session.getUsername());
        }
    }
    
    /**
     * Inicia el proceso de logout: deshabilita el botón para evitar pulsaciones
     * múltiples, llama a {@link AuthService#logout(Runnable)} de forma asíncrona
     * y, al completar, abre la ventana de {@link LoginGUI} y cierra el dashboard.
     */
    private void doLogout(){
        jButtonLogout.setEnabled(false);
        jButtonLogout.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        authService.logout(() ->{
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        this.dispose();
        });
    }
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelWelcomeUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlCBottom;
    private javax.swing.JPanel pnlCCenter;
    private javax.swing.JPanel pnlCTop;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
