/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ticketmaster.ticketplusclient.gui;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.*;

/**
 *
 * @author Erik
 */
public class DashboardUserGUI extends DashboardBaseGUI {

    public DashboardUserGUI(){
        super();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void setupRoleDashboard() {
        JPanel centerPanel = getCenterPanel();
        centerPanel.setLayout(new BorderLayout(10, 10));

        JPanel statsPanel = buildStatsPanel();
        centerPanel.add(statsPanel, BorderLayout.NORTH);

        JPanel ticketPanel = buildTicketPanel();
        centerPanel.add(ticketPanel, BorderLayout.CENTER);
    }

    private JPanel buildStatsPanel() {
        JPanel panel = new JPanel(new GridLayout(1, 3, 10, 0));
        panel.setBackground(new Color(34, 40, 44));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        panel.add(buildStatCard("Open tickets", "1"));
        panel.add(buildStatCard("Awaitin Reply", "2"));
        panel.add(buildStatCard("Closed", "3"));

        return panel;
    }

    private JPanel buildStatCard(String title, String value) {
        JPanel card = new JPanel(new BorderLayout());
        card.setBackground(new Color(21, 25, 28));
        card.setBorder(BorderFactory.createEmptyBorder(12, 16, 12, 16));
        card.setPreferredSize(new Dimension(0, 80));

        JLabel titleLabel = new JLabel(title);
        titleLabel.setForeground(new Color(180, 180, 180));

        JLabel valueLabel = new JLabel(value);
        valueLabel.setForeground(Color.WHITE);
        valueLabel.setFont(valueLabel.getFont().deriveFont(28f));

        card.add(titleLabel, BorderLayout.NORTH);
        card.add(valueLabel, BorderLayout.CENTER);
        return card;
    }

    private JPanel buildTicketPanel() {
        JPanel panel = new JPanel();
        panel.setBackground(new Color(21, 25, 28));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JLabel placeholder = new JLabel("....");
        placeholder.setForeground(new Color(120, 120, 120));
        panel.add(placeholder);

        return panel;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
