/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ticketmaster.ticketplusclient.gui;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.*;

/**
 * Panel de control específico para usuarios con rol de Agente (ADMIN) en TicketPlus.
 *
 * <p>Extiende {@link DashboardBaseGUI} e implementa el método
 * {@link #setupRoleDashboard()} del patrón Template Method para personalizar
 * el área central del dashboard con información relevante para un agente:
 * tarjetas de estadísticas de tickets y un panel de gestión de tickets.</p>
 *
 * <p>Los datos mostrados son de momento estáticos (simulados); se conectarán
 * con el servidor en sprints posteriores a través de {@link com.ticketmaster.ticketplusclient.api.DataAPI}.</p>
 *
 * @author Christian
 * @see DashboardBaseGUI
 */
public class DashboardAgentGUI extends DashboardBaseGUI {

    /**
     * Crea una nueva instancia del dashboard de agente, delegando la
     * inicialización base a {@link DashboardBaseGUI#DashboardBaseGUI()}.
     */
    public DashboardAgentGUI(){
        super();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Configura el contenido específico del dashboard para el rol de Agente.
     *
     * <p>Añade al panel central un panel de estadísticas en la zona norte
     * (con tarjetas de tickets abiertos, resueltos hoy y asignados) y un
     * panel de gestión de tickets en la zona central.</p>
     */
    protected void setupRoleDashboard() {
        JPanel centerPanel = getCenterPanel();
        centerPanel.setLayout(new BorderLayout(10, 10));
        centerPanel.add(new TicketListPanel(centerPanel), BorderLayout.CENTER);

        /*JPanel statsPanel = buildStatsPanel();
        centerPanel.add(statsPanel, BorderLayout.NORTH);*/

        /*JPanel ticketPanel = buildTicketPanel();
        centerPanel.add(ticketPanel, BorderLayout.CENTER);*/
    }

    /**
     * Construye el panel de estadísticas del agente con tres tarjetas:
     * tickets abiertos, resueltos hoy y asignados al agente.
     *
     * @return panel {@link JPanel} con el layout de estadísticas en cuadrícula
     */
    private JPanel buildStatsPanel() {
        JPanel panel = new JPanel(new GridLayout(1, 3, 10, 0));
        panel.setBackground(new Color(34, 40, 44));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        panel.add(buildStatCard("Open tickets", "12"));
        panel.add(buildStatCard("Resolved today", "5"));
        panel.add(buildStatCard("Assigned to me", "3"));

        return panel;
    }

    /**
     * Crea una tarjeta de estadística individual con título y valor numérico.
     *
     * @param title etiqueta descriptiva de la estadística
     * @param value valor numérico a mostrar en la tarjeta
     * @return panel {@link JPanel} con la tarjeta de estadística maquetada
     */
    private JPanel buildStatCard(String title, String value) {
        JPanel card = new JPanel(new BorderLayout());
        card.setBackground(new Color(21, 25, 28));
        card.setBorder(BorderFactory.createEmptyBorder(12, 16, 12, 16));
        card.setPreferredSize(new Dimension(0, 80));

        JLabel titleLabel = new JLabel(title);
        titleLabel.setForeground(new Color(180, 180, 180));

        JLabel valueLabel = new JLabel(value);
        valueLabel.setForeground(Color.WHITE);
        valueLabel.setFont(valueLabel.getFont().deriveFont(28f));

        card.add(titleLabel, BorderLayout.NORTH);
        card.add(valueLabel, BorderLayout.CENTER);
        return card;
    }

    /**
     * Construye el panel principal de gestión de tickets del agente.
     * Actualmente muestra un marcador de posición; se completará en sprints
     * posteriores con la tabla de tickets real.
     *
     * @return panel {@link JPanel} del área de tickets (placeholder)
     */
    private JPanel buildTicketPanel() {
        JPanel panel = new JPanel();
        panel.setBackground(new Color(21, 25, 28));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JLabel placeholder = new JLabel("....");
        placeholder.setForeground(new Color(120, 120, 120));
        panel.add(placeholder);

        return panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
