/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ticketmaster.ticketplusclient.gui;

import com.ticketmaster.ticketplusclient.model.LoginResponse;
import com.ticketmaster.ticketplusclient.session.AuthService;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * Ventana de inicio de sesión de la aplicación de escritorio TicketPlus.
 *
 * <p>Es la primera ventana que ve el usuario al arrancar la aplicación.
 * Recoge las credenciales (nombre de usuario y contraseña), las valida
 * localmente (campos no vacíos) y las envía al servidor a través de
 * {@link AuthService#login(String, String, AuthService.AuthCallback)}.</p>
 *
 * <p>Según el rol retornado por el servidor, redirige al dashboard
 * correspondiente mediante {@link #openDashboard(String)}:
 * <ul>
 *   <li>{@code ADMIN} → {@link DashboardAgentGUI}</li>
 *   <li>{@code USER}  → {@link DashboardUserGUI}</li>
 *   <li>otros roles   → {@link DashboardBaseGUI} (pantalla base)</li>
 * </ul>
 * </p>
 *
 * <p>Durante la espera de respuesta del servidor, el botón de login se
 * deshabilita y muestra un cursor de espera para mejorar la experiencia
 * de usuario. Se restaura automáticamente en caso de error.</p>
 *
 * @author Christian / Erik
 * @see AuthService
 * @see DashboardAgentGUI
 * @see DashboardUserGUI
 */
public class LoginGUI extends javax.swing.JFrame {

    /** Referencia al dashboard que se abrirá tras un login exitoso. */
    private DashboardBaseGUI dashboard;
    
    /** Servicio de autenticación que gestiona la comunicación con el servidor. */
    private final AuthService authService;

    /**
     * Crea e inicializa la ventana de login, configurando el servicio de
     * autenticación y centrando la ventana en pantalla.
     */
    public LoginGUI() {
        this.authService = new AuthService();
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanelLogin = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        UserPassPanel = new javax.swing.JPanel();
        UserPanel = new javax.swing.JPanel();
        UserTextField = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        PassPanel = new javax.swing.JPanel();
        PassLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        RememberMePanel = new javax.swing.JPanel();
        RememberMeCheckBox = new javax.swing.JCheckBox();
        ForgotLabel = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        DontHaveAccountPanel = new javax.swing.JPanel();
        DontHaveAccountLabel = new javax.swing.JLabel();
        CentralPanelLogin = new javax.swing.JPanel();
        iconTruckLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LeftPanelLogin.setBackground(new java.awt.Color(21, 25, 28));
        LeftPanelLogin.setPreferredSize(new java.awt.Dimension(415, 400));

        WelcomePanel.setBackground(new java.awt.Color(21, 25, 28));
        WelcomePanel.setPreferredSize(new java.awt.Dimension(400, 150));

        WelcomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome Back");

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(WelcomeLabel)
                .addGap(135, 135, 135))
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(WelcomeLabel)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        LeftPanelLogin.add(WelcomePanel);

        UserPassPanel.setBackground(new java.awt.Color(21, 25, 28));
        UserPassPanel.setPreferredSize(new java.awt.Dimension(400, 150));

        UserPanel.setBackground(new java.awt.Color(21, 25, 28));
        UserPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        UserPanel.setLayout(new java.awt.BorderLayout(4, 4));

        UserTextField.setBackground(new java.awt.Color(102, 102, 102));
        UserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextFieldActionPerformed(evt);
            }
        });
        UserPanel.add(UserTextField, java.awt.BorderLayout.CENTER);

        UserLabel.setBackground(new java.awt.Color(21, 25, 28));
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("User Account");
        UserPanel.add(UserLabel, java.awt.BorderLayout.PAGE_START);

        UserPassPanel.add(UserPanel);

        PassPanel.setBackground(new java.awt.Color(21, 25, 28));
        PassPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        PassPanel.setLayout(new java.awt.BorderLayout(4, 4));

        PassLabel.setBackground(new java.awt.Color(21, 25, 28));
        PassLabel.setForeground(new java.awt.Color(255, 255, 255));
        PassLabel.setText("Password");
        PassPanel.add(PassLabel, java.awt.BorderLayout.PAGE_START);

        PasswordTextField.setBackground(new java.awt.Color(102, 102, 102));
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });
        PassPanel.add(PasswordTextField, java.awt.BorderLayout.CENTER);

        UserPassPanel.add(PassPanel);

        RememberMePanel.setBackground(new java.awt.Color(21, 25, 28));
        RememberMePanel.setMinimumSize(new java.awt.Dimension(85, 25));
        RememberMePanel.setPreferredSize(new java.awt.Dimension(250, 25));
        RememberMePanel.setLayout(new java.awt.BorderLayout());

        RememberMeCheckBox.setBackground(new java.awt.Color(21, 25, 28));
        RememberMeCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        RememberMeCheckBox.setText("Remember me");
        RememberMeCheckBox.setFocusPainted(false);
        RememberMeCheckBox.setFocusable(false);
        RememberMeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RememberMeCheckBoxActionPerformed(evt);
            }
        });
        RememberMePanel.add(RememberMeCheckBox, java.awt.BorderLayout.WEST);

        ForgotLabel.setForeground(new java.awt.Color(0, 102, 153));
        ForgotLabel.setText("Forgot yor password?");
        RememberMePanel.add(ForgotLabel, java.awt.BorderLayout.EAST);

        UserPassPanel.add(RememberMePanel);

        LeftPanelLogin.add(UserPassPanel);

        LoginPanel.setBackground(new java.awt.Color(21, 25, 28));
        LoginPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        LoginButton.setBackground(new java.awt.Color(34, 40, 44));
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setFocusPainted(false);
        LoginButton.setPreferredSize(new java.awt.Dimension(250, 30));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(LoginButton);

        LeftPanelLogin.add(LoginPanel);

        DontHaveAccountPanel.setBackground(new java.awt.Color(21, 25, 28));
        DontHaveAccountPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        DontHaveAccountLabel.setText("Don't have an account yet? Sign up.");
        DontHaveAccountPanel.add(DontHaveAccountLabel);

        LeftPanelLogin.add(DontHaveAccountPanel);

        getContentPane().add(LeftPanelLogin, java.awt.BorderLayout.WEST);

        CentralPanelLogin.setBackground(new java.awt.Color(34, 40, 44));
        CentralPanelLogin.setPreferredSize(new java.awt.Dimension(400, 430));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 80);
        flowLayout1.setAlignOnBaseline(true);
        CentralPanelLogin.setLayout(flowLayout1);

        iconTruckLabel.setIcon(new ImageIcon(getClass().getResource("/icons/logo_ticketplus.png")));
        CentralPanelLogin.add(iconTruckLabel);

        getContentPane().add(CentralPanelLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void RememberMeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RememberMeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RememberMeCheckBoxActionPerformed

    /**
     * Manejador del evento de click sobre el botón de login.
     *
     * <p>Valida que los campos no estén vacíos, deshabilita el botón durante
     * la petición de red y delega la autenticación en
     * {@link AuthService#login(String, String, AuthService.AuthCallback)}.
     * Según el resultado, llama a {@link #openDashboard(String)} o a
     * {@link #showDialog(String)} con el mensaje de error.</p>
     *
     * @param evt evento de acción generado por el botón de login
     */
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        String username = UserTextField.getText();
        String password = new String(PasswordTextField.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            showDialog("Usuario y contraseña no pueden estar vacíos");
            return;
        } 
        
        LoginButton.setEnabled(false);
        LoginButton.setText("Conectando...");
        LoginButton.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        authService.login(username, password, new AuthService.AuthCallback(){
            
            @Override
            public void onSuccess(LoginResponse response){
                openDashboard(response.getRole());
            }
            
            @Override
            public void onError(String errorMessage){
                restoreLoginButton();
                showDialog(errorMessage);
                
            }   
            
        });
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * Abre el dashboard correspondiente al rol del usuario autenticado y
     * cierra la ventana de login.
     *
     * <p>Utiliza un switch sobre el rol (en mayúsculas) para instanciar el
     * dashboard adecuado:
     * <ul>
     *   <li>{@code ADMIN} → {@link DashboardAgentGUI}</li>
     *   <li>{@code USER}  → {@link DashboardUserGUI}</li>
     *   <li>otros         → {@link DashboardBaseGUI}</li>
     * </ul>
     * </p>
     *
     * @param role rol del usuario recibido en la respuesta de login del servidor
     */
    private void openDashboard(String role){
        
        switch(role.toUpperCase()){
            case "ADMIN":
                dashboard = new DashboardAgentGUI();
                break;
            case "USER":
                dashboard = new DashboardUserGUI();
                break;
            default:
                dashboard = new DashboardBaseGUI();
                break;
        }

        dashboard.setVisible(true);
        this.dispose();
    }
    
    /**
     * Muestra un diálogo modal de error.
     *
     * @param message mensaje a mostrar al usuario en el diálogo
     */
    private void showDialog(String message){
        UIManager.put("OptionPane.background", new Color(30, 40, 44));
                    UIManager.put("Panel.background", new Color(30, 40, 44));
                    UIManager.put("OptionPane.messageForeground", Color.WHITE);
                    JOptionPane.showMessageDialog(this, message);
    }
    
    /**
     * Restaura el botón de login a su estado original (habilitado, texto "Login"
     * y cursor por defecto) tras un intento de login fallido.
     */
    private void restoreLoginButton(){
        LoginButton.setEnabled(true);
        LoginButton.setText("Login");
        LoginButton.setCursor(Cursor.getDefaultCursor());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CentralPanelLogin;
    private javax.swing.JLabel DontHaveAccountLabel;
    private javax.swing.JPanel DontHaveAccountPanel;
    private javax.swing.JLabel ForgotLabel;
    private javax.swing.JPanel LeftPanelLogin;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPanel PassPanel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JCheckBox RememberMeCheckBox;
    private javax.swing.JPanel RememberMePanel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JPanel UserPassPanel;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel iconTruckLabel;
    // End of variables declaration//GEN-END:variables
}
